// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package prod

import (
	"fmt"
	"log"
	"magnet-test-task/env"
	"magnet-test-task/internal/config"
	"magnet-test-task/pkg/storage"
	"os"
)

// Injectors from wire.go:

func InitializeBox(cfg *config.Config) (*env.Box, func(), error) {
	storage := provideStorage(cfg)
	box := NewBox(storage)
	return box, func() {
	}, nil
}

// wire.go:

func provideStorage(cfg *config.Config) *storage.Storage {
	if err := os.MkdirAll(cfg.SQLLite.Path, 0750); err != nil {
		log.Fatal("database directory is not accessible: ", err)
	}
	dsn := fmt.Sprintf("%s/%s?mode=rw", cfg.SQLLite.Path, cfg.SQLLite.Name)
	s, err := storage.New(dsn)
	if err != nil {
		log.Fatal(err)
	}

	return s
}
